### ISSUE TITLE
Not compatible with bifunctors-5.6 , semialign-1.3, semigroupoids-6, transformers-0.6, these-1.2

### ISSUE THREAD

**Issue by ysangkok** [ssbothwell/monoidal-functors#29]
Compatibility with this version would make it possible to upgrade Stackage

* https://github.com/commercialhaskell/stackage/issues/6910
* https://github.com/commercialhaskell/stackage/issues/6857
* https://github.com/commercialhaskell/stackage/issues/6909

**Comment by ysangkok** [comment]
Also not compatible with semialign-1.3

**Comment by ysangkok** [comment]
Also missing compatibility for semigroupoids-6, transformers-0.6, these-1.2. Might be best to just run `cabal outdated`.

**Comment by ysangkok** [comment]
@solomon-b Have you seen this?

**Comment by solomon-b** [comment]
@ysangkok sorry I missed this! I'll take a look tomorrow and try to sort it all out.

**Comment by ysangkok** [comment]
Thank you @solomon-b , but I see that the tightened bound of `base` now disallows GHC 9.6:

```
/tmp $ cd monoidal-functors-0.2.2.0 
/tmp/monoidal-functors-0.2.2.0 $ cabal outdated
Outdated dependencies:
base >=4.12 && <4.18 (latest: 4.18.0.0)
```

**Comment by solomon-b** [comment]
@ysangkok Oh I haven't actually started using 9.6 or testing any of my libraries with it. I can make another minor release to allow newer `base`.

**Comment by ysangkok** [comment]
Thank you!

**Comment by solomon-b** [comment]
Thank you!
